-- AlterTable
ALTER TABLE "feedback" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "lessons" ALTER COLUMN "lesson_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "meetings" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "payments" ALTER COLUMN "paid_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "students" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "syllabuses" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ(0);
