version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate

  pre_build:
    commands:
      - node --version
      - pnpm --version
      - pnpm install --frozen-lockfile

  build:
    commands:
      - pnpm build

  post_build:
    commands:
      - cp -r .next/static .next/standalone/.next/static
      # 배포 관련 파일들을 standalone 폴더로 복사
      - cp -r .ebextensions .next/standalone/
      - mkdir -p .next/standalone/.platform
      - cp -r .platform/. .next/standalone/.platform/ 2>/dev/null || true
      - cp -r prisma .next/standalone/
      - cp Procfile .next/standalone/
      - cp prisma.config.mjs .next/standalone/
#      # Prisma CLI 복사 (migrate deploy 실행용)
#      - cp -r node_modules/prisma .next/standalone/node_modules/
#      - cp -r node_modules/@prisma .next/standalone/node_modules/
      - echo "Build completed on $(date)"

artifacts:
  base-directory: .next/standalone
  files:
    - .next/**/*
    - .platform/**/*
    - .ebextensions/*
    - prisma/**/*
    - server.js
    - package.json
    - prisma.config.mjs
    - Procfile
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
    - .next/cache/**/*
    - /root/.local/share/pnpm/store/**/*
